[versions]
agp = "8.1.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.0"
material = "1.10.0"
activity = "1.6.1"
constraintlayout = "2.1.4"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
jxl = { group = "net.sourceforge.jexcelapi", name = "jxl", version = "2.6.12" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

